### ISSUE TITLE
feat: macos support

### ISSUE THREAD

**Issue by danielgomezrico** [rohitsangwan01/pocketbase_server_flutter#1]
This is specially useful when you want to create a client/server application on a local network, where you can put your computer as the server and the apps as clients for it.

# Current
Supported platforms:
- iOS
- Android

# Expected
- MacOS is also supported

**Comment by rohitsangwan01** [comment]
@danielgomezrico pocketbase already supports desktops, you can download mac version from here https://github.com/pocketbase/pocketbase/releases
